import {
  Post,
  Ideia,
  HistoricoItem,
  ArquivoItem,
  Perfil,
  ContaConectada,
  MetricaDiaria,
  IntegracaoConfig,
  DEFAULT_ROLE_PERMISSIONS,
  GoogleDriveFolderMapping,
  MetaCampaign,
  MetaAdSet,
  MetaAd,
  MetaCreative,
  MetaPixelConfig,
  AuditLog,
} from '@/types';

// Helper to format dates relative to today
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_PROFILES: Perfil[] = [
  {
    id: 'p-1',
    nome: 'Lucas Silva',
    email: 'lucas@metamaxima.com.br',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    cargo: 'Head de Conteúdo & Estratégia',
    role: 'gestor',
    status: 'ativo',
    permissoes: DEFAULT_ROLE_PERMISSIONS.gestor,
    senha: '123456',
  },
  {
    id: 'p-2',
    nome: 'Mariana Costa',
    email: 'mariana@metamaxima.com.br',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    cargo: 'Copywriter & Roteirista',
    role: 'social_media',
    status: 'ativo',
    permissoes: DEFAULT_ROLE_PERMISSIONS.social_media,
    senha: '123456',
  },
  {
    id: 'p-3',
    nome: 'Pedro Santos',
    email: 'pedro@metamaxima.com.br',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    cargo: 'Editor de Vídeo & Motion',
    role: 'editor',
    status: 'ativo',
    permissoes: DEFAULT_ROLE_PERMISSIONS.editor,
    senha: '123456',
  },
  {
    id: 'p-4',
    nome: 'Camila Rocha',
    email: 'camila@metamaxima.com.br',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    cargo: 'Diretora de Operações',
    role: 'admin',
    status: 'ativo',
    permissoes: DEFAULT_ROLE_PERMISSIONS.admin,
    senha: '123456',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    titulo: '5 Erros que Fazem uma Empresa Perder Clientes no Instagram',
    data_publicacao: getRelativeDate(1), // Amanhã
    hora_publicacao: '18:30',
    tipo: 'reels_video',
    etapa_funil: 'topo',
    status: 'a_gravar',
    prioridade: 'alta',
    plataforma: 'instagram',
    responsavel: 'Lucas Silva',
    tags: ['Instagram', 'Erros', 'Vendas'],
    gancho: 'Se sua empresa faz isso no Instagram, você provavelmente está perdendo vendas todos os dias.',
    roteiro_desenvolvimento: '1. Bio confusa sem proposta de valor clara.\n2. Postar sem CTA no final.\n3. Não responder directs em menos de 1 hora.\n4. Focar em seguidores em vez de engajamento qualificado.',
    roteiro_prova: 'Analisamos 40 contas de clientes no último trimestre e aquelas que corrigiram esses 4 pontos dobraram a taxa de conversão em 30 dias.',
    cta: 'Salve este conteúdo para aplicar na sua conta ainda hoje.',
    legenda: 'Você comete algum desses erros na sua empresa? Conta aqui nos comentários ou salve para revisar com sua equipe! 🚀 #marketingdigital #instagramparanegocios #vendas',
    observacoes: 'Gravar no estúdio com iluminação lateral. Usar câmera Sony A7III e microfone de lapela DJI.',
    thumbnail_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500&auto=format&fit=crop&q=80',
    classificacao: 'organico_patrocinado',
    uso_trafego_pago: 'em_teste',
    meta_campaign_id: 'camp-1',
    meta_ad_id: 'ad-2',
    drive_file_id: 'drive_file_p1',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p1/view',
    drive_folder_id: 'drive_f_02',
    drive_folder_name: '02_A_Gravar_Roteiros',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'post-2',
    titulo: 'Checklist Prático: Como Montar um Carrossel Infinito no Canva',
    data_publicacao: getRelativeDate(3),
    hora_publicacao: '12:00',
    tipo: 'carrossel',
    etapa_funil: 'meio',
    status: 'gravado',
    prioridade: 'normal',
    plataforma: 'instagram',
    responsavel: 'Mariana Costa',
    tags: ['Design', 'Carrossel', 'Tutorial'],
    gancho: 'O segredo dos carrosséis que retêm 80% mais atenção do leitor.',
    roteiro_desenvolvimento: 'Slide 1: Capa magnética com elemento cortado.\nSlide 2 a 5: Conteúdo sequencial com quebra visual contínua.\nSlide 6: Conclusão direta.\nSlide 7: CTA clara com convite para salvar.',
    roteiro_prova: 'Nossa taxa média de salvamentos em carrossel é 4.2x maior do que posts estáticos.',
    cta: 'Comente "CARROSSEL" para receber nosso grid editável gratuito.',
    legenda: 'Quer aprender o passo a passo para criar carrosséis profissionais no Canva que prendem o leitor do início ao fim? Arraste para o lado e confira! 👉',
    observacoes: 'Mariana já entregou o roteiro e os textos dos slides. Falta exportar os assets no Illustrator.',
    thumbnail_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=500&auto=format&fit=crop&q=80',
    classificacao: 'organico',
    uso_trafego_pago: 'nao_utilizado',
    drive_file_id: 'drive_file_p2',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p2/view',
    drive_folder_id: 'drive_f_03',
    drive_folder_name: '03_Gravados_Brutos',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'post-3',
    titulo: 'Estudo de Caso: +340% em Leads para Clínica Odontológica em 45 Dias',
    data_publicacao: getRelativeDate(4),
    hora_publicacao: '19:00',
    tipo: 'resultado',
    etapa_funil: 'fundo',
    status: 'a_editar',
    prioridade: 'urgente',
    plataforma: 'instagram',
    responsavel: 'Pedro Santos',
    tags: ['Case', 'Odonto', 'Performance'],
    gancho: 'Como transformamos R$ 2.400 em mais de R$ 38.000 em procedimentos fechados.',
    roteiro_desenvolvimento: '1. Diagnóstico do gargalo: leads chegavam mas não compareciam às consultas.\n2. Ajuste na esteira: anúncio de conscientização + vídeo do Dr. Rafael explicando o tratamento.\n3. Automação de lembretes no WhatsApp.',
    roteiro_prova: 'Prints reais do gerenciador de anúncios Meta Ads e depoimento em áudio do cliente.',
    cta: 'Clique no link da bio e solicite um diagnóstico gratuito para sua clínica.',
    legenda: 'Mais um resultado expressivo para nossa carteira! Veja como estruturamos a estratégia de ponta a ponta. 📈',
    observacoes: 'Pedro precisa aplicar animações de motion nos prints de números para dar dinamismo.',
    thumbnail_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&auto=format&fit=crop&q=80',
    classificacao: 'patrocinado',
    uso_trafego_pago: 'ativo',
    meta_campaign_id: 'camp-1',
    meta_adset_id: 'adset-1',
    meta_ad_id: 'ad-1',
    meta_creative_id: 'cr-1',
    drive_file_id: 'drive_file_p3',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p3/view',
    drive_folder_id: 'drive_f_04',
    drive_folder_name: '04_Em_Edicao_Projetos',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'post-4',
    titulo: 'Tutorial Rápido: Automatizando Respostas de Stories com Manychat',
    data_publicacao: getRelativeDate(-2), // 2 dias atrás
    hora_publicacao: '15:00',
    tipo: 'reels_video',
    etapa_funil: 'meio',
    status: 'editado',
    prioridade: 'alta',
    plataforma: 'instagram',
    responsavel: 'Mariana Costa',
    tags: ['Automação', 'Manychat', 'Stories'],
    gancho: 'Pare de responder manualmente "Qual o valor?" centenas de vezes no direct.',
    roteiro_desenvolvimento: 'Passo a passo no painel do Manychat conectando a palavra-chave ao fluxo automatizado com entrega instantânea do link.',
    roteiro_prova: 'Economia de mais de 15 horas semanais para o time de atendimento da agência.',
    cta: 'Envie a palavra "AUTOMACAO" no direct para receber o fluxo montado.',
    legenda: 'Seus clientes querem respostas rápidas. Quem responde primeiro, fecha primeiro. Veja esse tutorial!',
    observacoes: 'Vídeo já editado no CapCut. Falta aprovação do cliente para agendar.',
    thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
    classificacao: 'organico',
    uso_trafego_pago: 'nao_utilizado',
    drive_file_id: 'drive_file_p4',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p4/view',
    drive_folder_id: 'drive_f_05',
    drive_folder_name: '05_Revisao_Aprovacao',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 6).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'post-5',
    titulo: 'Os Segredos do Algoritmo do Instagram para 2026',
    data_publicacao: getRelativeDate(2),
    hora_publicacao: '18:30',
    tipo: 'carrossel',
    etapa_funil: 'topo',
    status: 'agendado',
    prioridade: 'normal',
    plataforma: 'instagram',
    responsavel: 'Lucas Silva',
    tags: ['Algoritmo', 'Tendências', 'Reels'],
    gancho: 'O que realmente mudou na distribuição orgânica do Instagram em 2026.',
    roteiro_desenvolvimento: 'Foco absoluto em compartilhamentos privados (DM) e taxa de conclusão nos primeiros 4 segundos.',
    roteiro_prova: 'Declarações oficiais e testes comparativos em 12 contas da agência.',
    cta: 'Compartilhe este post com seu sócio ou time de marketing.',
    legenda: 'O algoritmo não é seu inimigo, ele só busca retenção. Aprenda como jogar de acordo com as novas regras!',
    observacoes: 'Agendado no Meta Business Suite para publicação automática.',
    thumbnail_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=500&auto=format&fit=crop&q=80',
    classificacao: 'organico',
    uso_trafego_pago: 'nao_utilizado',
    drive_file_id: 'drive_file_p5',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p5/view',
    drive_folder_id: 'drive_f_07',
    drive_folder_name: '07_Agendados',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'post-6',
    titulo: 'Como Fechamos R$ 45k de Contratos em 30 Dias com Conteúdo Orgânico',
    data_publicacao: getRelativeDate(-5),
    hora_publicacao: '20:00',
    tipo: 'resultado',
    etapa_funil: 'fundo',
    status: 'postado',
    prioridade: 'normal',
    plataforma: 'instagram',
    responsavel: 'Mariana Costa',
    tags: ['Case Interno', 'Agência', 'Vendas'],
    gancho: 'Sem gastar 1 centavo em tráfego pago, validamos nosso funil de conteúdo.',
    roteiro_desenvolvimento: 'Estrutura do conteúdo de fundo de funil: dor latente + solução proprietária + prova inquestionável.',
    roteiro_prova: 'Print do nosso próprio CRM com os contratos assinados e valores.',
    cta: 'Mande mensagem no direct para agendar sua consultoria diagnóstica.',
    legenda: 'Conteúdo quando tem método gera faturamento. Já superou 3.4k de alcance orgânico!',
    observacoes: 'Postado com sucesso! Já superou 3.4k de alcance e 24 salvamentos.',
    thumbnail_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop&q=80',
    classificacao: 'organico',
    uso_trafego_pago: 'nao_utilizado',
    drive_file_id: 'drive_file_p6',
    drive_file_url: 'https://drive.google.com/file/d/drive_file_p6/view',
    drive_folder_id: 'drive_f_08',
    drive_folder_name: '08_Postados_Finalizados',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 24 * 10).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
  {
    id: 'post-7',
    titulo: 'A Anatomia de um Gancho Irresistível nos Reels',
    data_publicacao: getRelativeDate(5),
    hora_publicacao: '17:00',
    tipo: 'reels_video',
    etapa_funil: 'topo',
    status: 'ideias',
    prioridade: 'alta',
    plataforma: 'instagram',
    responsavel: 'Lucas Silva',
    tags: ['Roteiro', 'Ganchos', 'Copywriting'],
    gancho: 'Se você não prender a atenção nos primeiros 2 segundos, seu vídeo já era.',
    roteiro_desenvolvimento: 'Demonstrar os 3 tipos de abertura: quebra de padrão visual, pergunta contraintuitiva e promessa de benefício.',
    roteiro_prova: 'Vídeos com esses ganchos mantiveram 68% de retenção média.',
    cta: 'Salve para usar na sua próxima gravação.',
    observacoes: 'Ideia convertida do banco de ideias. Roteiro em estruturação.',
    classificacao: 'organico_patrocinado',
    uso_trafego_pago: 'nao_utilizado',
    drive_folder_id: 'drive_f_01',
    drive_folder_name: '01_Ideias_e_Briefings',
    arquivado: false,
    ordem: 0,
    criado_em: new Date(Date.now() - 3600000 * 2).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const INITIAL_IDEAS: Ideia[] = [
  {
    id: 'ideia-1',
    titulo: 'A anatomia do gancho perfeito nos Reels',
    ideia: 'Mostrar os 3 primeiros segundos de vídeos virais e desmontar a técnica neurológica por trás deles.',
    gancho: 'Se você não prender a atenção nos primeiros 2 segundos, seu vídeo já era.',
    objetivo: 'Gerar autoridade e retenção.',
    publico: 'Criadores e gestores de tráfego',
    etapa_funil: 'topo',
    formato: 'Reels/Vídeo',
    referencia: 'Perfil @exemplo_viral no TikTok',
    cta: 'Salve para usar na sua próxima gravação.',
    observacoes: 'Já convertida em card de produção.',
    responsavel: 'Mariana Costa',
    prioridade: 'alta',
    categoria: 'autoridade',
    tags: ['Reels', 'Ganchos', 'Copywriting'],
    arquivado: false,
    post_id: 'post-7',
    criado_em: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    id: 'ideia-2',
    titulo: 'Bastidores da nossa reunião de planejamento semanal',
    ideia: 'Gravar trechos dinâmicos da equipe debatendo métricas e definindo os temas da semana.',
    gancho: 'É assim que planejamos 30 dias de conteúdo em apenas 2 horas.',
    objetivo: 'Conectar com o público e mostrar método de trabalho da agência.',
    publico: 'Donos de empresas e agências parceiras',
    etapa_funil: 'meio',
    formato: 'Stories',
    referencia: 'Vlog rápido estilo startup',
    cta: 'Você também tem reunião fixa de conteúdo na sua empresa?',
    observacoes: 'Gravar na segunda-feira pela manhã.',
    responsavel: 'Lucas Silva',
    prioridade: 'normal',
    categoria: 'bastidores',
    tags: ['Bastidores', 'Cultura', 'Rotina'],
    arquivado: false,
    criado_em: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'ideia-3',
    titulo: 'O maior erro de quem contrata agência de marketing',
    ideia: 'Esclarecer que a agência precisa de alinhamento com o time comercial para transformar lead em faturamento.',
    gancho: 'Contratar uma agência e não treinar o seu comercial é jogar dinheiro no lixo.',
    objetivo: 'Educar o mercado e qualificar potenciais clientes.',
    publico: 'Empresários e Diretores Comerciais',
    etapa_funil: 'fundo',
    formato: 'Carrossel',
    cta: 'Comente "DIAGNÓSTICO" se você quer alinhar tráfego e vendas.',
    observacoes: 'Post provocativo para gerar comentários qualificados.',
    responsavel: 'Camila Rocha',
    prioridade: 'alta',
    categoria: 'educacional',
    tags: ['Gestão', 'Vendas', 'Alinhamento'],
    arquivado: false,
    criado_em: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
  },
  {
    id: 'ideia-4',
    titulo: 'Tendências de Conteúdo Audiovisual para o Próximo Semestre',
    ideia: 'Análise de formatos: vídeos sem corte, áudios originais, estética lo-fi e vídeos verticais narrados.',
    gancho: 'Esses 3 formatos de vídeo vão dominar o feed nos próximos meses.',
    objetivo: 'Posicionamento de vanguarda e autoridade técnica.',
    publico: 'Social media e marcas inovadoras',
    etapa_funil: 'topo',
    formato: 'Reels/Vídeo',
    cta: 'Qual desses formatos você já testou na sua conta?',
    observacoes: 'Pedro pode separar trechos curtos de referência.',
    responsavel: 'Pedro Santos',
    prioridade: 'normal',
    categoria: 'tendencia',
    tags: ['Tendências', 'Vídeo', 'Audiovisual'],
    arquivado: false,
    criado_em: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
  },
  {
    id: 'ideia-5',
    titulo: 'Como recuperamos um cliente insatisfeito com transparência',
    ideia: 'Contar a história real de quando uma campanha inicial não performou e como recalculamos a rota para gerar ROI 5x.',
    gancho: 'O dia em que quase perdemos nosso maior cliente (e o que fizemos a respeito).',
    objetivo: 'Construir confiança inabalável e prova social sincera.',
    publico: 'Leads indecisos e clientes atuais',
    etapa_funil: 'fundo',
    formato: 'Post estático',
    cta: 'Transparência é um valor inegociável para você?',
    responsavel: 'Lucas Silva',
    prioridade: 'urgente',
    categoria: 'prova_social',
    tags: ['Transparência', 'Cultura', 'Clientes'],
    arquivado: false,
    criado_em: new Date(Date.now() - 3600000 * 18).toISOString(),
    atualizado_em: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
];

export const INITIAL_HISTORY: HistoricoItem[] = [
  {
    id: 'hist-1',
    post_id: 'post-1',
    usuario: 'Lucas Silva',
    acao: 'Status Atualizado',
    detalhe: 'Moveu de "Ideias" para "A Gravar"',
    criado_em: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'hist-2',
    post_id: 'post-2',
    usuario: 'Mariana Costa',
    acao: 'Status Atualizado',
    detalhe: 'Moveu de "A Gravar" para "Gravado"',
    criado_em: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'hist-3',
    post_id: 'post-3',
    usuario: 'Pedro Santos',
    acao: 'Prioridade Alterada',
    detalhe: 'Marcado como prioridade Urgente para entrega da semana',
    criado_em: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'hist-4',
    post_id: 'post-4',
    usuario: 'Mariana Costa',
    acao: 'Arquivo Anexado',
    detalhe: 'Adicionou vídeo editado tutorial_manychat_v2.mp4',
    criado_em: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'hist-5',
    post_id: 'post-6',
    usuario: 'Lucas Silva',
    acao: 'Publicação Concluída',
    detalhe: 'Marcado como "Postado" após publicação confirmada',
    criado_em: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
];

export const INITIAL_FILES: ArquivoItem[] = [
  {
    id: 'file-1',
    post_id: 'post-1',
    post_titulo: '5 Erros que Fazem uma Empresa Perder Clientes no Instagram',
    nome: 'roteiro_5_erros_v1.pdf',
    url: 'https://example.com/roteiro_5_erros.pdf',
    tamanho_bytes: 245000,
    tipo_mime: 'application/pdf',
    categoria_arquivo: 'documento',
    criado_em: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'file-2',
    post_id: 'post-2',
    post_titulo: 'Checklist Prático: Como Montar um Carrossel Infinito no Canva',
    nome: 'carrossel_canva_slides.zip',
    url: 'https://example.com/carrossel_canva_slides.zip',
    tamanho_bytes: 8420000,
    tipo_mime: 'application/zip',
    categoria_arquivo: 'imagem',
    criado_em: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
  },
  {
    id: 'file-3',
    post_id: 'post-3',
    post_titulo: 'Estudo de Caso: +340% em Leads para Clínica Odontológica em 45 Dias',
    nome: 'prints_meta_ads_odonto.png',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    tamanho_bytes: 1240000,
    tipo_mime: 'image/png',
    categoria_arquivo: 'referencia',
    criado_em: new Date(Date.now() - 3600000 * 16).toISOString(),
  },
  {
    id: 'file-4',
    post_id: 'post-4',
    post_titulo: 'Tutorial Rápido: Automatizando Respostas de Stories com Manychat',
    nome: 'tutorial_manychat_editado_v2.mp4',
    url: 'https://example.com/tutorial_manychat.mp4',
    tamanho_bytes: 45200000,
    tipo_mime: 'video/mp4',
    categoria_arquivo: 'video_editado',
    criado_em: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const INITIAL_INTEGRATIONS: IntegracaoConfig[] = [
  {
    id: 'int-drive',
    provedor: 'google_drive',
    nome: 'Google Drive Workspace',
    descricao: 'Sincronização de pastas por status do Kanban, upload direto de arquivos e movimentação automática.',
    status: 'conectado',
    ultima_sincronizacao: new Date(Date.now() - 3600000 * 1).toISOString(),
    credenciais: {
      client_id: '8192038102-mmd.apps.googleusercontent.com',
      client_secret: 'GOCSPX-****',
      root_folder_id: 'drive_root_mmd_2026',
      root_folder_name: 'Meta Máxima Digital - Produção de Conteúdo',
    },
  },
  {
    id: 'int-meta',
    provedor: 'meta_business',
    nome: 'Meta Business Suite & Instagram Graph API',
    descricao: 'Sincronização de métricas do Instagram (alcance, seguidores, engajamento, Reels) e páginas do Facebook.',
    status: 'conectado',
    ultima_sincronizacao: new Date(Date.now() - 3600000 * 2).toISOString(),
    credenciais: {
      business_id: 'bm_77491028401',
      ad_account_id: 'act_904812395',
      page_id: '1049281048201',
      ig_account_id: '178414002938102',
      access_token: 'EAABwz...',
    },
  },
  {
    id: 'int-meta-ads',
    provedor: 'meta_ads',
    nome: 'Meta Ads Manager API',
    descricao: 'Monitoramento de campanhas, conjuntos de anúncios, criativos e métricas de conversão (spend, CPL, ROAS).',
    status: 'conectado',
    ultima_sincronizacao: new Date(Date.now() - 3600000 * 1).toISOString(),
    credenciais: {
      ad_account_id: 'act_904812395',
      business_id: 'bm_77491028401',
      access_token: 'EAABwz...',
    },
  },
  {
    id: 'int-meta-pixel',
    provedor: 'meta_pixel',
    nome: 'Meta Conversions API & Pixel',
    descricao: 'Monitoramento de eventos de conversão no site, qualidade do sinal e jornada dos anúncios.',
    status: 'conectado',
    ultima_sincronizacao: new Date(Date.now() - 3600000 * 1).toISOString(),
    credenciais: {
      pixel_id: '1085306910535125',
      pixel_conversion_token: 'EAABwz...',
    },
  },
  {
    id: 'int-ga4',
    provedor: 'google_analytics',
    nome: 'Google Analytics 4 (GA4)',
    descricao: 'Monitoramento de tráfego web, sessões, novos usuários, taxa de conversão e origens de tráfego dos links da bio.',
    status: 'conectado',
    ultima_sincronizacao: new Date(Date.now() - 3600000 * 3).toISOString(),
    credenciais: {
      property_id: '419284012',
      measurement_id: 'G-7X9P4K2M',
      client_email: 'ga4-sync@metamaxima-prod.iam.gserviceaccount.com',
    },
  },
  {
    id: 'int-google-ads',
    provedor: 'google_ads',
    nome: 'Google Ads API',
    descricao: 'Sincronização de campanhas de rede de pesquisa, display, custo por clique (CPC), CTR e custo por lead.',
    status: 'desconectado',
    ultima_sincronizacao: undefined,
    credenciais: {
      customer_id: '',
      developer_token: '',
      client_id: '',
    },
  },
];

export const INITIAL_DRIVE_FOLDERS: GoogleDriveFolderMapping[] = [
  { id: 'gdf-gravado', status: 'gravado', folder_id: '19_TAUMLSHKnMnbrCnXh3W2Ckph9L_b0_', folder_name: 'Gravado' },
  { id: 'gdf-editado', status: 'editado', folder_id: '14Fejcns0sSJ7QNww9A8J-7hrVUU83drj', folder_name: 'Editado' },
  { id: 'gdf-postado', status: 'postado', folder_id: '1e1MiCRqtVB9xiqlJn-GbHFXipZThWahb', folder_name: 'Postado' },
];

export const INITIAL_CAMPAIGNS: MetaCampaign[] = [
  {
    id: 'camp-1',
    name: 'MMD - Captação Odonto Q3 [Leads]',
    objective: 'OUTCOME_LEADS',
    status: 'ACTIVE',
    daily_budget: 120.0,
    spend: 1840.5,
    leads: 142,
    cpl: 12.96,
    impressions: 54200,
    clicks: 1380,
    ctr: 2.55,
    created_time: '2026-08-15T10:00:00Z',
  },
  {
    id: 'camp-2',
    name: 'MMD - Remarketing Autoridade [Vendas]',
    objective: 'OUTCOME_SALES',
    status: 'ACTIVE',
    daily_budget: 80.0,
    spend: 960.0,
    leads: 38,
    cpl: 25.26,
    impressions: 26800,
    clicks: 890,
    ctr: 3.32,
    created_time: '2026-08-20T14:30:00Z',
  },
  {
    id: 'camp-3',
    name: 'MMD - Topo de Funil Reels [Alcance]',
    objective: 'OUTCOME_AWARENESS',
    status: 'PAUSED',
    lifetime_budget: 500.0,
    spend: 500.0,
    leads: 0,
    cpl: 0,
    impressions: 112000,
    clicks: 1420,
    ctr: 1.27,
    created_time: '2026-08-01T09:00:00Z',
  },
];

export const INITIAL_ADSETS: MetaAdSet[] = [
  {
    id: 'adset-1',
    campaign_id: 'camp-1',
    name: 'Aberto 25-50 anos - Raio 15km Clínica',
    status: 'ACTIVE',
    targeting_summary: 'Idade 25-50 anos, Raio 15km, Interesses: Saúde bucal, Odontologia estética',
    daily_budget: 70.0,
    spend: 1120.0,
    leads: 94,
    cpl: 11.91,
  },
  {
    id: 'adset-2',
    campaign_id: 'camp-1',
    name: 'Lookalike 1% Envolvidos Instagram 30D',
    status: 'ACTIVE',
    targeting_summary: 'Semelhante 1% aos usuários que engajaram com o Instagram da clínica',
    daily_budget: 50.0,
    spend: 720.5,
    leads: 48,
    cpl: 15.01,
  },
  {
    id: 'adset-3',
    campaign_id: 'camp-2',
    name: 'Visitantes da Landing Page 14D',
    status: 'ACTIVE',
    targeting_summary: 'Pixel Lead Page Viewers nos últimos 14 dias excluindo compradores',
    daily_budget: 80.0,
    spend: 960.0,
    leads: 38,
    cpl: 25.26,
  },
];

export const INITIAL_CREATIVES: MetaCreative[] = [
  {
    id: 'cr-1',
    name: 'Criativo 01 - Vídeo Case Odonto +340%',
    post_id: 'post-3',
    thumbnail_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&auto=format&fit=crop&q=80',
    title: 'Como aumentamos em 340% os leads qualificados para clínicas',
    body: 'Descubra a esteira validada que transforma visualizações em agendamentos reais na sua recepção.',
    format: '9:16 Vídeo Vertical (Reels/Stories)',
  },
  {
    id: 'cr-2',
    name: 'Criativo 02 - Carrossel 5 Erros que Fazem Perder Clientes',
    post_id: 'post-1',
    thumbnail_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500&auto=format&fit=crop&q=80',
    title: 'Sua empresa comete algum desses 5 erros no Instagram?',
    body: 'Veja os 5 pontos cegos que fazem sua empresa perder dinheiro e clientes todos os dias.',
    format: '1:1 Carrossel 6 Slides',
  },
];

export const INITIAL_ADS: MetaAd[] = [
  {
    id: 'ad-1',
    campaign_id: 'camp-1',
    adset_id: 'adset-1',
    name: 'AD01 - Vídeo Case Odonto +340%',
    creative_id: 'cr-1',
    post_id: 'post-3',
    status: 'ACTIVE',
    spend: 1120.0,
    impressions: 34800,
    reach: 26400,
    clicks: 920,
    ctr: 2.64,
    cpc: 1.22,
    cpm: 32.18,
    leads: 94,
    cpl: 11.91,
    conversions: 94,
    cpa: 11.91,
    revenue: 38400.0,
    roas: 34.28,
  },
  {
    id: 'ad-2',
    campaign_id: 'camp-1',
    adset_id: 'adset-2',
    name: 'AD02 - Carrossel 5 Erros no Instagram',
    creative_id: 'cr-2',
    post_id: 'post-1',
    status: 'ACTIVE',
    spend: 720.5,
    impressions: 19400,
    reach: 15200,
    clicks: 460,
    ctr: 2.37,
    cpc: 1.57,
    cpm: 37.14,
    leads: 48,
    cpl: 15.01,
    conversions: 48,
    cpa: 15.01,
    revenue: 14200.0,
    roas: 19.71,
  },
];

export const INITIAL_PIXEL_CONFIG: MetaPixelConfig = {
  pixel_id: '1085306910535125',
  name: 'Pixel Principal Meta Máxima Digital',
  status: 'ativo',
  last_event_time: new Date(Date.now() - 1000 * 90).toISOString(),
  diagnostics: 'Sinal saudável. API de Conversões (CAPI) e Pixel Web sincronizados. Qualidade de correspondência avançada: 8.8/10.',
  events: [
    {
      id: 'px-ev-1',
      pixel_id: '1085306910535125',
      event_name: 'PageView',
      event_count: 52410,
      last_fired_at: 'Há 2 minutos',
      url: 'https://metamaxima.com.br/',
    },
    {
      id: 'px-ev-2',
      pixel_id: '1085306910535125',
      event_name: 'ViewContent',
      event_count: 18920,
      last_fired_at: 'Há 5 minutos',
      url: 'https://metamaxima.com.br/planos',
    },
    {
      id: 'px-ev-3',
      pixel_id: '1085306910535125',
      event_name: 'Lead',
      event_count: 1580,
      last_fired_at: 'Há 14 minutos',
      url: 'https://metamaxima.com.br/obrigado-diagnostico',
    },
    {
      id: 'px-ev-4',
      pixel_id: '1085306910535125',
      event_name: 'Contact',
      event_count: 740,
      last_fired_at: 'Há 40 minutos',
      url: 'https://metamaxima.com.br/whatsapp',
    },
    {
      id: 'px-ev-5',
      pixel_id: '1085306910535125',
      event_name: 'CompleteRegistration',
      event_count: 310,
      last_fired_at: 'Há 1 hora',
      url: 'https://metamaxima.com.br/onboarding',
    },
  ],
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    user_id: 'p-1',
    user_name: 'Lucas Silva',
    action: 'MOVE_STATUS',
    entity_type: 'POST',
    entity_id: 'post-5',
    entity_title: 'Os Segredos do Algoritmo do Instagram para 2026',
    details: 'Status movido de "aprovado" para "agendado". Google Drive: arquivo sincronizado na pasta "08_Agendados_MetaSuite".',
    criado_em: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'log-2',
    user_id: 'p-2',
    user_name: 'Mariana Costa',
    action: 'CONVERT_IDEA',
    entity_type: 'IDEA',
    entity_id: 'ideia-1',
    entity_title: 'A anatomia do gancho perfeito nos Reels',
    details: 'Ideia do banco convertida diretamente em card no Kanban (ID: post-7)',
    criado_em: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'log-3',
    user_id: 'p-4',
    user_name: 'Camila Rocha',
    action: 'LINK_AD',
    entity_type: 'AD',
    entity_id: 'ad-1',
    entity_title: 'AD01 - Vídeo Case Odonto +340%',
    details: 'Conteúdo "Estudo de Caso Odonto" vinculado como criativo ativo na campanha "MMD - Captação Odonto Q3"',
    criado_em: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: 'log-4',
    user_id: 'p-3',
    user_name: 'Pedro Santos',
    action: 'UPLOAD_FILE',
    entity_type: 'FILE',
    entity_id: 'file-4',
    entity_title: 'tutorial_manychat_editado_v2.mp4',
    details: 'Vídeo editado finalizado e adicionado ao post "Tutorial Rápido: Automatizando Respostas de Stories"',
    criado_em: new Date(Date.now() - 3600000 * 60).toISOString(),
  },
];
